version: '3.4'

services:
  api:
    build:
      context: .
      target: dev
    image: jaegeon/fitclip:dev
    container_name: fitclip-dev
    environment:
      FITCLIP_ENV: development
    volumes:
      - .:/app
    ports:
      - 8000:8000
