version: '3.4'

services:
  api:
    build:
      context: .
      target: dev
    image: jaegeon/fitclib:dev
    container_name: fitclib-dev
    environment:
      FITCLIB_ENV: development
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: runserver 0.0.0.0:8000